#!/bin/bash

# This file is part of the Bodhi Linux Web Browser Manager.
#
# License: GPL-3.0 or later
#
# (c) Bodhi Linux Team (2022-2023)

echo "This script will install the Bodhi Linux Web Browser Manager."
read -p "Do you wish to continue? " -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "Compiling .po in .mo..."
	for po_file in ./po/*.po; do
		lang=$(basename "$po_file" .po)
		mo_dir="/usr/share/locale/$lang/LC_MESSAGES"
		mo_file="$mo_dir/browser-manager.mo"

		echo "→ $lang → $mo_file"
		mkdir -p "$mo_dir"
		msgfmt "$po_file" -o "$mo_file"
	done
	echo "Translations installed in /usr/share/locale/{lang}/LC_MESSAGES"
    exit 0
fi

